apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/otomato-gh/quote-charts.git
    targetRevision: HEAD
    path: ollama
    helm:
      valuesObject:
        ollama:
          models:
          - "qwen2.5:0.5b"
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
